name = input("ENTER YOUR NAME: ")
matric_no = input(str("ENTER YOUR MATRIC_NO: "))
sex = input("ENTER YOUR SEX: ")
department = input("ENTER YOUR DEPARTMENT: ")
level = input("ENTER YOUR LEVEL: ")
d_o_b = input("ENTER YOUR D_O_B: ")
age = int(input("ENTER YOUR AGE: "))
g.p = float(input("ENTER YOUR G.P: "))
weight = float(input("ENTER YOUR WEIGHT: "))
isMuslim = bool(input("ENTER YOUR ISMUSLIM:\n ")
print(name)
print(matric_no)
print(sex)
print(department)
print(level)
print(d_o_b)
print(age)
print(g.p)
print(weight)
print(isMuslim)
